[package]
name = "captain_hook"
version = "0.1.0"
authors = ["Aaron Ross <superhawk610@gmail.com>"]
edition = "2018"

[dependencies]
ws = "0.8.0"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
uuid = { version = "0.7.4", features = ["v4"] }
